version: '3.8'

services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: rs-devops-db
    volumes:
      - db:/bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=root
      - POSTGRESQL_DATABASE=devops-db
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=root
    networks:
      - rs-devops-network

  api-rocket:
    build:
      context: .
    container_name: rs-devops-api
    ports:
      - 3333:3333
    environment:
      # - DATABASE_URL=file:./dev.db
      # - DATABASE_URL=postgresql://admin:root@localhost:5432/devops-db
      - DATABASE_URL=postgresql://admin:root@rs-devops-db:5432/devops-db
    depends_on:
      - postgresql
    networks:
      - rs-devops-network

networks:
  rs-devops-network:
    driver: bridge

volumes:
  db:
